# Generated by Django 5.2 on 2025-04-19 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_clothingcategory_handicraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('department', 'Department'), ('product', 'Product'), ('material', 'Material'), ('purpose', 'Purpose'), ('technique', 'Technique'), ('food_subcategory', 'Food Subcategory')], default='department', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='materials',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'material'}, related_name='material_posts', to='api.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='purposes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'purpose'}, related_name='purpose_posts', to='api.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='techniques',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'technique'}, related_name='technique_posts', to='api.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, help_text='Article content with inline images', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Disabled', 'Disabled')], default='Active', max_length=100)),
                ('view', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'department'}, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Article',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/')),
                ('position', models.PositiveIntegerField(help_text='Position of the image in the article content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.article')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'constraints': [models.UniqueConstraint(fields=('post', 'image'), name='unique_post_image')],
            },
        ),
    ]
