# Generated by Django 5.2 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_category_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('department', 'Department'), ('product', 'Product')], default='department', max_length=20),
        ),
    ]
