# Generated by Django 5.2 on 2025-04-29 14:53

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=api.models.UnicodeSlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=api.models.UnicodeSlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=api.models.UnicodeSlugField(blank=True, null=True, unique=True),
        ),
    ]
