# Generated by Django 5.2 on 2025-04-29 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
