# Generated by Django 5.2 on 2025-05-20 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_date_field_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='default/default-user.jpg', null=True, upload_to='image'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
