# Generated by Django 5.2 on 2025-05-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_description'),
        ('api', '0014_convert_description_to_json'),
    ]

    operations = [
    ]
