# Generated by Django 5.2 on 2025-07-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_updates',
            field=models.BooleanField(default=False),
        ),
    ]
